apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: app-cluster
  region: us-east-1

nodeGroups:
  - name: nodegroup-1
    instanceType: m5.large
    desiredCapacity: 6
  - name: nodegroup-2
    instanceType: m5.xlarge
    desiredCapacity: 2
