releases:
  - name: rediscart
    chart: chart/redis
    values:
      - values/redis-values.yaml
      - appReplicas: "1"
      - volumeName: "rediscartdata"

  - name: emailservice
    chart: chart/microservice
    values:
      - values/email-service-values.yaml

  - name: cartservice
    chart: chart/microservice
    values:
      - values/cart-service-values.yaml

  - name: currencyservice
    chart: chart/microservice
    values:
      - values/currency-service-values.yaml

  - name: paymentservice
    chart: chart/microservice
    values:
      - values/payment-service-values.yaml

  - name: recommendationservice
    chart: chart/microservice
    values:
      - values/recommendation-service-values.yaml

  - name: productcatalogservice
    chart: chart/microservice
    values:
      - values/productcatalog-service-values.yaml

  - name: shippingservice
    chart: chart/microservice
    values:
      - values/shipping-service-values.yaml

  - name: adservice
    chart: chart/microservice
    values:
      - values/ad-service-values.yaml

  - name: checkoutservice
    chart: chart/microservice
    values:
      - values/checkout-service-values.yaml

  - name: frontendservice
    chart: chart/microservice
    values:
      - values/frontend-values.yaml
